name: CI
on: [push]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install dependencies
        run: |
          npm ci
      - name: Check format
        run: |
          npx prettier -c .
      - name: Run test
        run: |
          npm test
      - name: Run production build
        run: |
          npm run prod
  backend:
    runs-on: ubuntu-latest
    container: 'golang:latest'
    services:
      postgres:
        image: 'postgres:alpine'
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.17'
      - name: Check format
        run: |
          git add -A
          go fmt ./...
          git diff --exit-code &>/dev/null
      - name: Run test
        run: |
          go test -v ./...
        env:
          RUN_DB_TEST: '1'
          POSTGRES_HOST: 'postgres'
          POSTGRES_PORT: '5432'
